"""Build the 90-second Chinese CG narration master from locally cached neural TTS segments.

Inputs are generated by synthesize_cg_voiceover.py and converted to 22.05 kHz mono WAV.
The script keeps the timeline deterministic, adds a quiet industrial room bed, applies a
small radio-band EQ to comms lines, fades hard edges, and writes a PCM WAV suitable for
Blender/FFmpeg and Android SoundPool. No runtime network dependency is introduced.
"""
from __future__ import annotations
import json, math, pathlib, wave
import numpy as np
from scipy.signal import butter, sosfilt

ROOT = pathlib.Path(__file__).resolve().parents[2]
SR = 22050
DURATION = 90.0
N = int(SR * DURATION)
EDGE_DIR = ROOT / 'dist/cg/audio_candidates/edge_voice_segments'
MANIFEST = EDGE_DIR.with_suffix('.json')
BED_PATH = ROOT / 'app/src/main/assets/audio/industrial_loop.wav'
OUT_MASTER = ROOT / 'dist/cg/audio_candidates/steelfire_cg_voiceover_90s.wav'
OUT_ASSET = ROOT / 'app/src/main/assets/audio/cg/intro_voiceover_90s.wav'


def read_wav(path: pathlib.Path) -> np.ndarray:
    with wave.open(str(path), 'rb') as w:
        frames = w.readframes(w.getnframes())
        channels, width, rate = w.getnchannels(), w.getsampwidth(), w.getframerate()
    if width != 2 or rate != SR:
        raise RuntimeError(f'{path} must be 16-bit {SR} Hz; got width={width}, rate={rate}')
    x = np.frombuffer(frames, dtype='<i2').astype(np.float32) / 32768.0
    if channels > 1:
        x = x.reshape(-1, channels).mean(axis=1)
    return x


def fade(x: np.ndarray, fade_in: int, fade_out: int) -> np.ndarray:
    y = x.copy()
    if len(y):
        n = min(fade_in, len(y)); y[:n] *= np.linspace(0, 1, n, endpoint=False)
        n = min(fade_out, len(y)); y[-n:] *= np.linspace(1, 0, n, endpoint=False)
    return y


def radio_eq(x: np.ndarray) -> np.ndarray:
    # Compact comms texture: trim sub/air, keep speech intelligible.
    sos = butter(4, [280, 4200], btype='bandpass', fs=SR, output='sos')
    y = sosfilt(sos, x)
    return y * 0.82


def rms_db(x: np.ndarray) -> float:
    return 20.0 * math.log10(max(1e-8, float(np.sqrt(np.mean(x * x)))))


def write_wav(path: pathlib.Path, x: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    y = np.clip(x, -1.0, 1.0)
    with wave.open(str(path), 'wb') as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(SR)
        w.writeframes((y * 32767.0).astype('<i2').tobytes())


def main() -> None:
    segments = json.loads(MANIFEST.read_text(encoding='utf-8'))
    bed = read_wav(BED_PATH)
    bed = np.tile(bed, int(np.ceil(N / len(bed))))[:N]
    # The environment is intentionally quiet under speech; cinematic mix leaves headroom for SFX.
    mix = bed * 0.065
    # Very low-level noise keeps transitions from sounding digitally cut without masking consonants.
    rng = np.random.default_rng(90210)
    mix += rng.normal(0.0, 0.00045, N).astype(np.float32)
    for seg in segments:
        path = EDGE_DIR / f"{seg['id']}.wav"
        x = read_wav(path)
        if seg['id'].startswith('r'):
            x = radio_eq(x)
            gain = 0.78
        elif seg['id'].startswith('t'):
            gain = 0.94
        else:
            gain = 0.96
        x = fade(x * gain, int(SR * 0.035), int(SR * 0.11))
        start = int(round(float(seg['start']) * SR))
        end = min(N, start + len(x))
        if start < 0 or start >= N or end <= start:
            raise RuntimeError(f"invalid segment timing: {seg}")
        mix[start:end] += x[:end-start]
    # Master to -1 dBFS while preserving 10 dB peak headroom before final encode.
    peak = float(np.max(np.abs(mix)))
    if peak > 0.891:
        mix *= 0.891 / peak
    OUT_MASTER.parent.mkdir(parents=True, exist_ok=True)
    write_wav(OUT_MASTER, mix)
    OUT_ASSET.parent.mkdir(parents=True, exist_ok=True)
    write_wav(OUT_ASSET, mix)
    print(f'wrote {OUT_MASTER} ({DURATION:.1f}s, peak={np.max(np.abs(mix)):.3f}, rms={rms_db(mix):.1f}dBFS)')
    print(f'wrote {OUT_ASSET}')

if __name__ == '__main__':
    main()
